# This is a basic workflow to help you get started with Actions

name: Get ID Token from OIDC Provider


# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-id:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: prod

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Use action to get ID Token
        #uses: dwivedine/getIDToken-action@v1.5
        #with: 
         #   client_id: "Redundant"
          #  client_secret: "Redundant"
           # password: "Redundant"
            #scope: "Redundant"
        #uses: orgdwivedine/actionoidcclient@1.0.5
        uses: orgdwivedine/TS_GHOIDC_IDToken@v1.0.0
        id: tokenid
        
      
        
      - name: Echo the ID token value
        run: echo "The output is ${{ steps.tokenid.outputs.id_token }}"
        
      
